alert:
  name: iTAG Alert
  description: Make the iTAG beep for finding
  fields:
    entity_id:
      name: Device
      description: The iTAG device to alert
      required: true
      selector:
        entity:
          domain: sensor
          integration: itag_tracker
    duration:
      name: Duration
      description: Duration of beep in seconds
      required: false
      default: 10
      selector:
        number:
          min: 1
          max: 30
          unit_of_measurement: "seconds"